"""One-shot SQLite → Postgres data import for the HiveMind backend switch.

Moves every row of the repo-root ``hivemind.db`` (tasks, agent_metrics,
request_log) into the (empty) ``hivemind`` Postgres database whose schema
is created by :class:`hivemind.storage.db.Database` migration v1.
Standard library ``sqlite3`` + ``psycopg`` only (plus ``hivemind.storage.db``
for the target side).

Sources
-------
* **Rows** — ``hivemind.db`` at the repo root: the database written by the
  pre-migration scheduler.  The live file is schema-only today (0 rows in
  all three tables — the import must be a no-op pass there), but the tool
  has to handle populated sources too.  Opened ``mode=ro``; never written.

Import strategy
---------------
1. Open the target with ``hivemind.storage.db.Database`` → migration v1
   runs (schema first; idempotent on an already-migrated DB).
2. COPY each table ``FROM STDIN`` in the order tasks → agent_metrics →
   request_log, then advance the identity sequences of the two log tables
   (below).

Why COPY with raw pre-formatted bytes instead of psycopg ``write_row``
or ``executemany``?  (a) ``executemany`` is per-row parse/plan overhead;
COPY is the bulk wire protocol.  (b) ``copy.write_row`` escapes with
*text*-format rules (backslash escaping), which is wrong for
``FORMAT csv`` (quote doubling), and a text-format empty field cannot
distinguish ``''`` from NULL on the PG side.  Writing the CSV bytes
ourselves is deterministic: with ``FORMAT csv`` a *quoted* empty field
is ``''`` and an *unquoted* empty field is NULL — exactly the SQLite
semantics where empty TEXT is ``''`` and ``None`` is NULL.  Every field
is quoted (``"`` doubled), so embedded commas, newlines and quotes in
JSON are safe; numbers are quoted too (PG parses ``"123"`` fine).  JSON
columns pass through as the stored JSON text — ``jsonb``'s text
representation *is* JSON text, so COPY accepts it without a cast.
SQLite stored all JSON via ``json.dumps``, so no re-serialization is
needed (and empty JSON strings are pre-validated to not exist before
any COPY starts).

Identity sequences: COPY inserts explicit ``id`` values, which do NOT
advance ``GENERATED BY DEFAULT AS IDENTITY`` sequences — the next
application insert would collide with the highest copied id.  After
each log-table COPY, ``setval(pg_get_serial_sequence(...))`` to
``MAX(id)`` restores the invariant.  Empty tables are skipped:
``setval(seq, NULL)`` happens to be a silent no-op on PG 17, but it is
pointless and not worth betting on older servers.

Idempotency
-----------
``--fresh`` (default) truncates the target tables first (``RESTART
IDENTITY``, so the sequences reset too); ``--no-fresh`` skips any table
that already has rows.  ``DRY_RUN=1`` (or ``--dry-run``) prints what
would be imported and touches nothing — the migrations a real import
runs are *not* applied (the target is opened with a plain sync psycopg
connection that makes no writes).

Verification (run at the end of a real import)
----------------------------------------------
Per-table source-vs-target counts, asserted equal (exit 1 on mismatch),
plus the applied-migration versions on the target.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sqlite3
import sys
import time
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

import psycopg

try:
    from hivemind.storage.db import Database
except ImportError:  # allow direct `python3 tools/pg-migrate/import_sqlite.py`
    sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))
    from hivemind.storage.db import Database  # noqa: F811

# ---------------------------------------------------------------------------
# Table registry
# ---------------------------------------------------------------------------
#
# Import order.  ``json_cols`` are TEXT-JSON columns in SQLite that become
# JSONB in Postgres; their stored text passes through COPY untouched (sqlite
# wrote them via json.dumps, so they are already valid JSON text).


@dataclass(frozen=True)
class _TableSpec:
    name: str
    json_cols: frozenset[str]


_TABLES: list[_TableSpec] = [
    _TableSpec("tasks", frozenset({"dependencies", "metadata"})),
    _TableSpec("agent_metrics", frozenset()),
    _TableSpec("request_log", frozenset()),
]

_TYPE_REAL = "REAL"
_TYPE_INT = "INTEGER"

_JSON_EMPTY_CHECK = "SELECT COUNT(*) FROM {table} WHERE {col} = '' OR {col} = ' '"

_NAME_WIDTH = 22


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _log(msg: str) -> None:
    print(msg, flush=True)


def _csv_field(value: bytes | None) -> bytes:
    """One CSV field: NULL → unquoted empty; anything else quoted, ``"`` doubled.

    With ``FORMAT csv`` an unquoted empty field is NULL and a *quoted*
    empty field is ``''`` — this is what maps SQLite ``None`` vs ``""``
    correctly.  Doubling the quote char is the only csv escape; commas,
    newlines and backslashes need no special handling inside quotes.
    """
    if value is None:
        return b""
    return b'"' + value.replace(b'"', b'""') + b'"'


# ---------------------------------------------------------------------------
# SQLite source access
# ---------------------------------------------------------------------------


def _open_sqlite(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.execute("PRAGMA query_only = ON")
    return conn


def _source_counts(conn: sqlite3.Connection) -> dict[str, int]:
    out: dict[str, int] = {}
    for spec in _TABLES:
        out[spec.name] = int(conn.execute(f"SELECT COUNT(*) FROM {spec.name}").fetchone()[0])
    return out


def _sqlite_columns(conn: sqlite3.Connection, table: str) -> list[tuple[str, str]]:
    """(name, declared type) pairs in declared order, from PRAGMA table_info."""
    return [(row[1], row[2].upper()) for row in conn.execute(f"PRAGMA table_info({table})")]


def _check_json_columns(conn: sqlite3.Connection, spec: _TableSpec) -> None:
    """Fail before any COPY if a JSON column holds '' or whitespace.

    Such a value cannot be cast to jsonb and would abort the COPY
    mid-stream; a cheap upfront scan turns that into a clean error.
    HiveMind writes JSON via json.dumps, so this is a guard, not an
    expected path.
    """
    for col in spec.json_cols:
        n = int(conn.execute(_JSON_EMPTY_CHECK.format(table=spec.name, col=col)).fetchone()[0])
        if n:
            raise RuntimeError(
                f"{spec.name}.{col}: {n} row(s) hold an empty/whitespace string — "
                "not valid JSON for jsonb; aborting before COPY"
            )


# ---------------------------------------------------------------------------
# Row → COPY bytes
# ---------------------------------------------------------------------------


def _iter_table_rows(
    conn: sqlite3.Connection,
    spec: _TableSpec,
    names: list[str],
) -> Iterator[bytes]:
    """Stream CSV lines for one table, transforming sqlite values in place.

    Types come from the sqlite declaration: INTEGER → BIGINT passthrough
    (``str(int(v))``), REAL → DOUBLE PRECISION (``repr(float(v))`` — the
    float64 form round-trips the ``time.time()`` floats the app stores
    bit-exact), TEXT → TEXT or JSONB (raw JSON text passthrough).
    None → NULL (unquoted empty csv field).
    """
    types = dict(_sqlite_columns(conn, spec.name))
    cur = conn.execute(f"SELECT {', '.join(names)} FROM {spec.name}")
    for row in cur:
        fields = []
        for name, value in zip(names, row):
            if value is None:
                fields.append(_csv_field(None))
                continue
            col_type = types[name]
            if col_type == _TYPE_INT:
                fields.append(_csv_field(str(int(value)).encode()))
            elif col_type == _TYPE_REAL:
                fields.append(_csv_field(repr(float(value)).encode()))
            elif col_type == "TEXT":
                fields.append(_csv_field(value.encode("utf-8")))
            else:
                raise RuntimeError(f"{spec.name}.{name}: unexpected sqlite type {col_type!r}")
        yield b",".join(fields) + b"\n"


# ---------------------------------------------------------------------------
# Target-side checks and COPY
# ---------------------------------------------------------------------------


async def _pg_columns(db: Database, table: str) -> list[str]:
    """Column names in ordinal order, from information_schema (dict rows)."""
    cur = await db.db.execute(
        """
        SELECT column_name FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = %s
         ORDER BY ordinal_position
        """,
        (table,),
    )
    rows = await cur.fetchall()
    return [row["column_name"] for row in rows]


async def _assert_schemas_align(db: Database, conn: sqlite3.Connection, spec: _TableSpec) -> list[str]:
    """Names and order must match the Postgres migration DDL exactly.

    Migration v1's DDL was ported "verbatim: same column names and order"
    (db.py), so this is a cheap drift guard.  Returns the shared column
    order (PG's, which equals sqlite's).
    """
    sqlite_names = [n for n, _ in _sqlite_columns(conn, spec.name)]
    pg_names = await _pg_columns(db, spec.name)
    if sqlite_names != pg_names:
        raise RuntimeError(
            f"{spec.name}: sqlite columns {sqlite_names} != postgres columns {pg_names} — "
            "aborting (schema drift between the two backends)"
        )
    return pg_names


async def _copy_table(db: Database, spec: _TableSpec, conn: sqlite3.Connection, names: list[str]) -> int:
    """COPY one table FROM STDIN (FORMAT csv, raw bytes).  Returns rows."""
    cols = ", ".join(names)
    n = 0
    t0 = time.perf_counter()
    _log(f"  {spec.name:<{_NAME_WIDTH}}: COPY FROM STDIN…")
    async with db.db.cursor() as cur:
        async with cur.copy(f"COPY {spec.name} ({cols}) FROM STDIN WITH (FORMAT csv)") as copy:
            for line in _iter_table_rows(conn, spec, names):
                await copy.write(line)
                n += 1
    dt = time.perf_counter() - t0
    _log(f"  {spec.name:<{_NAME_WIDTH}}: {n:>10,} rows in {dt:.1f}s ({n / dt:,.0f}/s)")
    return n


# ---------------------------------------------------------------------------
# Identity sequences
# ---------------------------------------------------------------------------


async def _fix_sequences(db: Database, imported: dict[str, int]) -> None:
    """Advance identity sequences past the copied explicit ids.

    COPY inserted explicit ``id`` values, which do NOT advance
    ``GENERATED BY DEFAULT AS IDENTITY`` sequences — the next app insert
    would collide with the highest copied id.  ``setval`` to ``MAX(id)``
    restores the invariant.  Empty tables are skipped: ``setval(seq,
    NULL)`` is a silent no-op on PG 17 but pointless and not worth
    betting on older servers.  (The two log tables are the only identity
    columns; ``tasks`` has a TEXT primary key.)
    """
    for table in ("agent_metrics", "request_log"):
        if not imported[table]:
            _log(f"  {table:<{_NAME_WIDTH}}: empty — sequence untouched")
            continue
        await db.db.execute(f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), (SELECT MAX(id) FROM {table}))")
        _log(f"  {table:<{_NAME_WIDTH}}: identity sequence advanced to MAX(id)")


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


async def _verify_counts(db: Database, src_conn: sqlite3.Connection) -> None:
    """Per-table source-vs-target counts, asserted equal.

    The sqlite source has no schema_migrations table (the PG side creates
    it during migration v1), so that row is reported from the target
    only — ``applied_versions`` is a sanity print, not a comparison.
    Any data-table mismatch raises SystemExit(1).
    """
    src = _source_counts(src_conn)
    _log("")
    _log("=== COUNT VERIFICATION (sqlite source vs postgres target) ===")
    _log(f"  {'table':<{_NAME_WIDTH}} {'sqlite':>13} {'postgres':>13}  status")
    ok = True
    for spec in _TABLES:
        cur = await db.db.execute(f"SELECT COUNT(*) AS n FROM {spec.name}")
        pg = int((await cur.fetchone())["n"])
        s = src[spec.name]
        status = "OK" if s == pg else "MISMATCH"
        ok &= s == pg
        _log(f"  {spec.name:<{_NAME_WIDTH}} {s:>13,} {pg:>13,}  {status}")
    cur = await db.db.execute("SELECT COUNT(*) AS n FROM schema_migrations")
    pg_sm = int((await cur.fetchone())["n"])
    applied = await db.applied_versions()
    _log(f"  {'schema_migrations':<{_NAME_WIDTH}} {'n/a (sqlite)':>13} {pg_sm:>13,}  applied {applied}")
    _log("")
    if not ok:
        _log("FAIL: one or more tables did not match")
        raise SystemExit(1)
    _log("ALL COUNTS MATCH")


# ---------------------------------------------------------------------------
# Dry run
# ---------------------------------------------------------------------------


def _dry_run(args: argparse.Namespace) -> None:
    src_path = args.src.expanduser()
    _log("=== DRY RUN — nothing will be written ===")
    _log(f"  source sqlite : {src_path}")
    _log(f"  target dsn    : {args.dsn}")
    if not src_path.exists():
        raise SystemExit(f"source sqlite not found: {src_path}")
    conn = _open_sqlite(src_path)
    src = _source_counts(conn)
    conn.close()
    _log("")
    _log(f"  {'table':<{_NAME_WIDTH}} {'rows':>13}")
    for spec in _TABLES:
        _log(f"  {spec.name:<{_NAME_WIDTH}} {src[spec.name]:>13,}")
    # Target side: plain sync connection — no writes, migrations NOT run.
    with psycopg.connect(args.dsn) as conn:
        for spec in _TABLES:
            exists = conn.execute(
                """
                SELECT COUNT(*) FROM information_schema.tables
                 WHERE table_schema = 'public' AND table_name = %s
                """,
                (spec.name,),
            ).fetchone()[0]
            if not exists:
                n = 0
                state = "absent — migration v1 creates it"
            else:
                n = conn.execute(f"SELECT COUNT(*) FROM {spec.name}").fetchone()[0]
                state = "would TRUNCATE (--fresh)" if args.fresh else ("would SKIP" if n else "empty")
            _log(f"  target {spec.name:<16}: {n:>13,} rows — {state}")
    _log("")
    _log("DRY RUN COMPLETE — no writes performed. Re-run without DRY_RUN=1 to import.")
    _log("Note: a real import first opens the target with hivemind.storage.db.Database,")
    _log("applying migration v1 (tables created if absent, schema_migrations v1 row).")


# ---------------------------------------------------------------------------
# Real import
# ---------------------------------------------------------------------------


async def _real_import(args: argparse.Namespace) -> None:
    src_path = args.src.expanduser()
    if not src_path.exists():
        raise SystemExit(f"source sqlite not found: {src_path}")
    t_start = time.perf_counter()
    _log("=== HIVEMIND SQLITE → POSTGRES IMPORT ===")
    _log(f"  source sqlite : {src_path}")
    _log(f"  target dsn    : {args.dsn}")
    if args.fresh:
        _log("  mode          : --fresh (target tables truncated first)")
    else:
        _log("  mode          : --no-fresh (non-empty tables skipped)")

    src_conn = _open_sqlite(src_path)
    src = _source_counts(src_conn)
    _log("")
    _log("  DRY-RUN SUMMARY (what is about to happen):")
    for spec in _TABLES:
        _log(f"    import {spec.name:<15} {src[spec.name]:>13,} rows")
    _log("")

    # Schema first: migration v1 runs on open (idempotent otherwise).
    t0 = time.perf_counter()
    db = Database(args.dsn)
    await db.connect()
    _log(
        f"  schema          : migration v1 applied in {time.perf_counter() - t0:.1f}s "
        f"(applied {await db.applied_versions()})"
    )

    # --fresh: wipe the data tables (never schema_migrations).  RESTART
    # IDENTITY also resets the two identity sequences, so the setval
    # fix-up below always starts from a known baseline.
    skip: set[str] = set()
    if args.fresh:
        t0 = time.perf_counter()
        await db.db.execute("TRUNCATE tasks, agent_metrics, request_log RESTART IDENTITY")
        _log(f"  truncate        : tasks, agent_metrics, request_log in {time.perf_counter() - t0:.1f}s")
    else:
        for spec in _TABLES:
            cur = await db.db.execute(f"SELECT COUNT(*) AS n FROM {spec.name}")
            n = int((await cur.fetchone())["n"])
            if n:
                skip.add(spec.name)
                _log(f"  skip (--no-fresh): {spec.name} already has {n:,} rows")

    imported: dict[str, int] = {}
    for spec in _TABLES:
        if spec.name in skip:
            cur = await db.db.execute(f"SELECT COUNT(*) AS n FROM {spec.name}")
            imported[spec.name] = int((await cur.fetchone())["n"])
            continue
        _check_json_columns(src_conn, spec)
        names = await _assert_schemas_align(db, src_conn, spec)
        imported[spec.name] = await _copy_table(db, spec, src_conn, names)

    await _fix_sequences(db, imported)
    await _verify_counts(db, src_conn)

    dt = time.perf_counter() - t_start
    _log(f"=== IMPORT COMPLETE in {dt:.1f}s ===")
    await db.close()
    src_conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "One-shot SQLite → Postgres import for HiveMind. DRY_RUN=1 or --dry-run prints the plan and exits."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--src", default="hivemind.db", type=Path, help="source SQLite database")
    parser.add_argument(
        "--dsn",
        default="postgresql://hivemind@localhost:5432/hivemind",
        help="target PG DSN",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--fresh",
        dest="fresh",
        action="store_true",
        default=True,
        help="truncate target tables before importing (default)",
    )
    group.add_argument(
        "--no-fresh",
        dest="fresh",
        action="store_false",
        help="skip tables that already have rows",
    )
    parser.add_argument("--dry-run", action="store_true", help="print plan only (DRY_RUN=1 too)")
    args = parser.parse_args()

    if args.dry_run or os.environ.get("DRY_RUN") == "1":
        _dry_run(args)
    else:
        asyncio.run(_real_import(args))


if __name__ == "__main__":
    main()
